
searched_terms = [
    "one health",
    "one medicine",
    "animal",
    "human",
    "environment",
    "ecosystem",
    "ecohealth",
    "antimicrobial resistance",
    "antibiotic resistance",
    "drug resistance",
    "multidrug resistance",
    "resistance",
    "AMR",
    "ARB",
    "AR",
    "MDR",
    "dairy",
    "cow",
    "beef",
    "cattle",
    "poultry",
    "swine",
    "chicken",
    "pig",
    "turkey",
    "fish",
    "porcine",
    "bovine",
    "soil",
    "agriculture",
    "wastewater",
    "pharmaceutical",
    "drinking water",
    "groundwater",
    "surface water",
    "compost",
    "manure",
    "biosolids",
    "aquaculture"]